# Generated by Django 4.2.1 on 2023-06-01 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('is_manager', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postid', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content_type', models.IntegerField(default=0)),
                ('text', models.CharField(max_length=200)),
                ('media_url', models.CharField(max_length=300)),
                ('location_x', models.FloatField()),
                ('location_y', models.FloatField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentid', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('content_type', models.CharField(max_length=200)),
                ('media_url', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=200)),
                ('postid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.post')),
            ],
        ),
    ]
