# Generated by Django 4.2.1 on 2023-06-01 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='postid',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='username',
            new_name='user',
        ),
    ]
